version: "3.12"

services:
  67c74c43706b59b673a8d664_service:
    build: .
    container_name: 67c74c43706b59b673a8d664_container
    # Adjust your desired external port mapping here. For example:
    # "8502:8501" means the app is internally on 8501, but externally accessible on 8502.
    ports:
      - "8524:8501"
    environment:
      - PORT=8501  # This must match the internal port used by Streamlit
    restart: always
